version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserpassword
    ports:
      - '3307:3306'
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: healthggApp
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: my-secret-pw
      DATABASE_NAME: mydatabase
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis

volumes:
  db-data:
  redis-data:
