version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserpassword
    ports:
      - '3307:3306'
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: nestjs-container
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: myuser
      DATABASE_PASSWORD: myuserpassword
      DATABASE_NAME: mydatabase
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db-data:
