name: Docker Compose Develop CI/CD

on:
  pull_request:
    branches: ['develop']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set ENV
        run: |
          echo "${{ secrets.DOT_ENV_DEV }}" >> .env

      - name: Deploy ELK Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }} # 서버 IP 주소
          username: ${{ secrets.SSH_USERNAME_DEV }} # 서버 사용자 이름
          password: ${{ secrets.SSH_PASSWORD_DEV }} # SSH 개인 키
          port: ${{ secrets.SSH_PORT_DEV }} # SSH 포트 (기본값: 22)
          script: |
            cd /home/ubuntu/healthgg-back 
            echo "${{ secrets.DOT_ENV_DEV }}" >> .env
            git pull origin develop
            docker-compose down               
            docker-compose up -d --build
