name: Docker Compose Develop CI/CD

on:
  pull_request:
    branches: ['develop']

jobs:
  build-and-deploy:
    runs-on: develop

    steps:
      - uses: actions/checkout@v3

      - name: Set ENV
        run: |
          echo "${{ secrets.DOT_ENV_DEV }}" > .env

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Reset local branch to match remote
        run: |
          git fetch origin
          git reset --hard origin/develop

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: Stop existing containers
        run: docker-compose down

      - name: Start new containers
        run: docker-compose up -d --build

      - name: Clean up
        run: docker system prune -af
