name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed

jobs:
  build:
    #러너 실행
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull ystar500833177/healthgg:latest
      - name: Delete Old docker container
        run: sudo docker rm -f healthgg || true
      - name: Run Docker Container
        run: sudo docker run -d -p 3000:3000 -e NODE_ENV=development --network healthgg-network --name healthgg-container ystar500833177/healthgg:latest
