name: Docker Compose Develop CI/CD

on:
  pull_request:
    branches: ['develop']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set ENV
        run: |
          echo "ELASTIC_VERSION=${{ secrets.DOT_ENV_DEV }}" >> .env

      # - name: Copy files to remote server
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST_DEV }}
      #     username: ${{ secrets.SSH_USERNAME_DEV }}
      #     password: ${{ secrets.SSH_PASSWORD_DEV }}
      #     port: ${{ secrets.SSH_PORT_DEV }}
      #     source: './' # 현재 작업 디렉토리의 모든 파일을 복사
      #     target: '/home/ubuntu/healthgg-back' # 원격 서버의 타겟 디렉토리

      - name: Deploy ELK Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }} # 서버 IP 주소
          username: ${{ secrets.SSH_USERNAME_DEV }} # 서버 사용자 이름
          password: ${{ secrets.SSH_PASSWORD_DEV }} # SSH 개인 키
          port: ${{ secrets.SSH_PORT_DEV }} # SSH 포트 (기본값: 22)
          script: |
            cd /home/ubuntu/healthgg-back 
            docker-compose down      
            docker-compose pull      
            docker-compose up -d
