name: development PR

on:
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Update this with your desired Node.js version

      # - name: Set ENV
      #   run: |
      #     echo "${{ secrets.DOT_ENV_DEV }}" > .env.development
      #   shell: bash

      - name: SSH into VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST_DEV }}
          username: ${{ secrets.VM_HOST_USERNAME_DEV }}
          key: ${{ secrets.VM_HOST_PRIVATE_KEY_DEV }}
          script: |
            docker run
