name: Docker Develop Image CI/CD

on:
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set ENV
        run: |
          echo "${{ secrets.DOT_ENV_DEV }}" > .env.development
        shell: bash
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/healthgg:latest -f dockerfile.development .

      - name: taging
        run: docker tag ${{secrets.DOCKERHUB_USERNAME}}/healthgg:latest ${{secrets.DOCKERHUB_USERNAME}}/healthgg:latest

      - name: Push to Dockerhub
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/healthgg:latest

      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USERNAME_DEV }}
          password: ${{ secrets.SSH_PASSWORD_DEV }}
          port: ${{ secrets.SSH_PORT_DEV }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            echo "${{ secrets.DOCKER_COMPOSE_YML }}" > /home/ubuntu/app/docker-compose.yml
            docker-compose down
            docker pull ${{secrets.DOCKERHUB_USERNAME}}/healthgg:latest
            docker-compose pull
            docker-compose up -d
