name: Docker Compose Develop CI/CD

on:
  pull_request:
    branches: ['develop']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses:
          actions/checkout@v3

          # Docker Compose 설치
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: SET ENV
        run: echo "${{ secrets.DOT_ENV_DEV }}" >> .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # - name: Build and push Docker images
      #   run: |
      #     docker-compose -f docker-compose.yml build
      #     docker-compose -f docker-compose.yml push

      - name: Deploy ELK Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }} # 서버 IP 주소
          username: ${{ secrets.SSH_USERNAME_DEV }} # 서버 사용자 이름
          password: ${{ secrets.SSH_PASSWORD_DEV }} # SSH 개인 키
          port: ${{ secrets.SSH_PORT_DEV }} # SSH 포트 (기본값: 22)
          script: |
            cd /home/ubuntu/healthgg-back 
            echo "${{ secrets.DOT_ENV_DEV }}" >> .env
            git checkout develop
            git pull origin develop
            docker-compose down
            docker-compose up -d --build
