name: Docker Compose Develop CI/CD

on:
  pull_request:
    branches: ['develop']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: /home/ubuntu/app # 소스를 특정 디렉토리로 가져옴

      - name: Deploy ELK Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }} # 서버 IP 주소
          username: ${{ secrets.SSH_USERNAME_DEV }} # 서버 사용자 이름
          password: ${{ secrets.SSH_PASSWORD_DEV }} # SSH 개인 키
          port: ${{ secrets.SSH_PORT_DEV }} # SSH 포트 (기본값: 22)
          script: |
            cd /home/ubuntu/app  
            docker-compose down      
            docker-compose pull      
            docker-compose up -d
