name: Docker Production Image CI

on:
  pull_request:
    branches: ['production']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set ENV
        run: |
          echo "${{ secrets.DOT_ENV_PRO }}" > .env.production
        shell: bash
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/healthggproduction:latest -f dockerfile.production .
      - name: taging
        run: docker tag ${{secrets.DOCKERHUB_USERNAME}}/healthggproduction:latest ${{secrets.DOCKERHUB_USERNAME}}/healthggproduction:latest
      - name: Push to Dockerhub
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/healthggproduction:latest
